In [1]:
import pandas as pd

In [2]:
# Inisialisasi Data
df = pd.read_csv('data_raw/indonesia_ecommerce_sales_challenging.csv', sep=';')
df.columns = df.columns.str.strip()

In [3]:
# Pengumpulan dan Pemahaman Data
df.info()
display(df.describe())

print(f'Total data pada dataset: {df.shape} [baris, kolom]')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18868 entries, 0 to 18867
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   order_id                            18868 non-null  object
 1   total_qty                           18585 non-null  float64
 2   total_weight_gr                     18868 non-null  int64
 3   total_returned_qty                  18868 non-null  int64
 4   Total Diskon                        18868 non-null  int64
 5   product_categories                  18868 non-null  object
 6   num_product_categories              18868 non-null  int64
 7   Status Pesanan                      18868 non-null  object
 8   Alasan Pembatalan                   18868 non-null  object
 9   Opsi Pengiriman                     18868 non-null  object
 10  Metode Pembayaran                   18585 non-null  object
 11  Kota/Kabupaten                      18868 non-null  object
 12  Provinsi                            18868 non-null  object
 13  Ongkos Kirim Dibayar oleh Pembeli   18868 non-null  int64
 14  Estimasi Potongan Biaya Pengiriman  18868 non-null  int64
 15  Total Pembayaran                    18868 non-null  int64
 16  Perkiraan Ongkos Kirim              18868 non-null  int64
 17  Waktu Pesanan Dibuat                18868 non-null  object
 18  order_date                          18680 non-null  object
dtypes: float64(1), int64(8), object(10)
memory usage: 2.7+ MB

,total_qty,total_weight_gr,total_returned_qty,Total Diskon,num_product_categories,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim
count,18585.000000,18868.000000,18868.000000,18868.000000,18868.000000,18868.000000,18868.000000,1.886800e+04,18868.000000
mean,2.565940,2021.273055,0.018709,424.220691,1.113473,4312.362678,10605.738552,5.099066e+04,18446.542612
std,7.799706,7044.934507,0.575668,10110.492750,0.491409,13900.862394,12482.329140,1.426189e+05,23076.099280
min,1.000000,10.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000
25%,1.000000,300.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.367500e+04,8000.000000
50%,1.000000,500.000000,0.000000,0.000000,1.000000,0.000000,9000.000000,2.180000e+04,11000.000000
75%,2.000000,1600.000000,0.000000,0.000000,1.000000,3000.000000,15000.000000,4.231125e+04,20000.000000
max,256.000000,375000.000000,70.000000,700000.000000,11.000000,584000.000000,312000.000000,3.076000e+06,624000.000000

Total data pada dataset: (18868, 19) [baris, kolom]

In [4]:
# Menghapus Duplikasi
print(f'Total baris duplikat: {df.duplicated().sum()}')
df.drop_duplicates(subset=['order_id'])

print(f'Total baris setelah menghapus duplikat: {df.duplicated().sum()}')

df.head(10)

Total baris duplikat: 0
Total baris setelah menghapus duplikat: 0

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,order_date
0,ORD_0000001,2.0,2000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,2024-04-01
1,ORD_0000002,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,2024-04-01
2,ORD_0000003,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,2024-04-01
3,ORD_0000004,2.0,400,0,0,Mangkok Sambal / Saus,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,2024-04-01
4,ORD_0000005,3.0,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,2024-04-01
5,ORD_0000006,2.0,1000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SPayLater,KAB. BANDUNG,JAWA BARAT,0,10000,40996,10000,2024-04-01 07:09,2024-04-01
6,ORD_0000007,1.0,1700,0,0,Nampan / Tray,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,SPayLater,KOTA TANGERANG,BANTEN,0,0,0,16000,2024-04-01 07:23,2024-04-01
7,ORD_0000008,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. BOGOR,JAWA BARAT,0,8000,18280,8000,2024-04-01 07:33,2024-04-01
8,ORD_0000009,1.0,500,0,0,Celengan,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-J&T Economy,Online Payment,KAB. GARUT,JAWA BARAT,0,0,0,16500,2024-04-01 07:56,2024-04-01
9,ORD_0000010,6.0,12900,0,0,"Aksesoris Mandi, Celengan, Keranjang",3,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. TEGAL,JAWA TENGAH,13000,20000,92800,33000,2024-04-01 08:27,2024-04-01

In [5]:
# Menangani Nilai Hilang
print(f'Jumlah data yang hilang pada dataset:\n{df.isnull().sum()} \n')

df = df.dropna(subset=['order_date', 'total_qty'])

df['Metode Pembayaran'] = df['Metode Pembayaran'].fillna('Unknown')

print(f'Jumlah data yang hilang pada dataset setelah ditangani:\n{df.isnull().sum()} \n')

df.head(10)

Jumlah data yang hilang pada dataset:
order_id                                0
total_qty                             283
total_weight_gr                         0
total_returned_qty                      0
Total Diskon                            0
product_categories                      0
num_product_categories                  0
Status Pesanan                          0
Alasan Pembatalan                       0
Opsi Pengiriman                         0
Metode Pembayaran                     283
Kota/Kabupaten                          0
Provinsi                                0
Ongkos Kirim Dibayar oleh Pembeli       0
Estimasi Potongan Biaya Pengiriman      0
Total Pembayaran                        0
Perkiraan Ongkos Kirim                  0
Waktu Pesanan Dibuat                    0
order_date                            188
dtype: int64

Jumlah data yang hilang pada dataset setelah ditangani:
order_id                              0
total_qty                             0
total_weight_gr                       0
total_returned_qty                    0
Total Diskon                          0
product_categories                    0
num_product_categories                0
Status Pesanan                        0
Alasan Pembatalan                     0
Opsi Pengiriman                       0
Metode Pembayaran                     0
Kota/Kabupaten                        0
Provinsi                              0
Ongkos Kirim Dibayar oleh Pembeli     0
Estimasi Potongan Biaya Pengiriman    0
Total Pembayaran                      0
Perkiraan Ongkos Kirim                0
Waktu Pesanan Dibuat                  0
order_date                            0
dtype: int64

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,order_date
0,ORD_0000001,2.0,2000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,2024-04-01
1,ORD_0000002,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,2024-04-01
2,ORD_0000003,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,2024-04-01
3,ORD_0000004,2.0,400,0,0,Mangkok Sambal / Saus,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,2024-04-01
4,ORD_0000005,3.0,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,2024-04-01
5,ORD_0000006,2.0,1000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SPayLater,KAB. BANDUNG,JAWA BARAT,0,10000,40996,10000,2024-04-01 07:09,2024-04-01
6,ORD_0000007,1.0,1700,0,0,Nampan / Tray,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,SPayLater,KOTA TANGERANG,BANTEN,0,0,0,16000,2024-04-01 07:23,2024-04-01
7,ORD_0000008,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. BOGOR,JAWA BARAT,0,8000,18280,8000,2024-04-01 07:33,2024-04-01
8,ORD_0000009,1.0,500,0,0,Celengan,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-J&T Economy,Online Payment,KAB. GARUT,JAWA BARAT,0,0,0,16500,2024-04-01 07:56,2024-04-01
9,ORD_0000010,6.0,12900,0,0,"Aksesoris Mandi, Celengan, Keranjang",3,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. TEGAL,JAWA TENGAH,13000,20000,92800,33000,2024-04-01 08:27,2024-04-01

In [6]:
# Standarisasi
df = df.rename(columns={
    'total_weight_gr': 'total_berat_gr',
    'total_returned_qty': 'total_pengembalian_qty',
    'product_categories': 'kategori_produk',
    'num_product_categories': 'jumlah_kategori_produk',
    'order_date': 'tanggal_pesanan'
})

df.head(10)

,order_id,total_qty,total_berat_gr,total_pengembalian_qty,Total Diskon,kategori_produk,jumlah_kategori_produk,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,tanggal_pesanan
0,ORD_0000001,2.0,2000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,2024-04-01
1,ORD_0000002,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,2024-04-01
2,ORD_0000003,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,2024-04-01
3,ORD_0000004,2.0,400,0,0,Mangkok Sambal / Saus,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,2024-04-01
4,ORD_0000005,3.0,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,2024-04-01
5,ORD_0000006,2.0,1000,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,SPayLater,KAB. BANDUNG,JAWA BARAT,0,10000,40996,10000,2024-04-01 07:09,2024-04-01
6,ORD_0000007,1.0,1700,0,0,Nampan / Tray,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,SPayLater,KOTA TANGERANG,BANTEN,0,0,0,16000,2024-04-01 07:23,2024-04-01
7,ORD_0000008,1.0,500,0,0,Celengan,1,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. BOGOR,JAWA BARAT,0,8000,18280,8000,2024-04-01 07:33,2024-04-01
8,ORD_0000009,1.0,500,0,0,Celengan,1,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-J&T Economy,Online Payment,KAB. GARUT,JAWA BARAT,0,0,0,16500,2024-04-01 07:56,2024-04-01
9,ORD_0000010,6.0,12900,0,0,"Aksesoris Mandi, Celengan, Keranjang",3,Selesai,Tidak dibatalkan,Hemat Kargo-SPX Hemat,Online Payment,KAB. TEGAL,JAWA TENGAH,13000,20000,92800,33000,2024-04-01 08:27,2024-04-01