In [1]:
import pandas as pd

In [2]:
# Inisialisasi Data
df = pd.read_csv('data_raw/synthetic_umkm_data.csv', sep=',')
df.columns = df.columns.str.strip()

In [3]:
# Inspeksi & Profiling Data
df.info()
display(df.describe())

print(f'Total data pada dataset: {df.shape} [baris, kolom]')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        150000 non-null  int64
 1   Monthly_Revenue           150000 non-null  int64
 2   Net_Profit_Margin (%)     150000 non-null  float64
 3   Burn_Rate_Ratio           150000 non-null  float64
 4   Transaction_Count         150000 non-null  int64
 5   Avg_Historical_Rating     150000 non-null  float64
 6   Review_Text               150000 non-null  object
 7   Review_Volatility         150000 non-null  float64
 8   Business_Tenure_Months    150000 non-null  int64
 9   Repeat_Order_Rate (%)     150000 non-null  float64
 10  Digital_Adoption_Score    150000 non-null  float64
 11  Peak_Hour_Latency         150000 non-null  object
 12  Location_Competitiveness  150000 non-null  int64
 13  Sentiment_Score           150000 non-null  float64
 14  Class                     150000 non-null  object
dtypes: float64(7), int64(5), object(3)
memory usage: 17.2+ MB

,ID,Monthly_Revenue,Net_Profit_Margin (%),Burn_Rate_Ratio,Transaction_Count,Avg_Historical_Rating,Review_Volatility,Business_Tenure_Months,Repeat_Order_Rate (%),Digital_Adoption_Score,Location_Competitiveness,Sentiment_Score
count,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,75000.500000,8.451726e+06,1.842272,0.969885,117.766667,4.061107,0.407203,91.006840,19.980521,3.546894,8.998807,-0.018946
std,43301.414527,5.291163e+06,15.002406,0.144039,42.618493,0.521698,0.166806,51.104736,8.021928,1.670303,2.828602,0.320534
min,1.000000,1.500000e+06,-35.000000,0.437000,9.000000,1.500000,0.060000,3.000000,2.000000,1.000000,1.000000,-0.650000
25%,37500.750000,4.745884e+06,-8.430000,0.869000,86.000000,3.770000,0.278000,47.000000,14.450000,2.260000,7.000000,-0.250000
50%,75000.500000,7.245678e+06,2.160000,0.966000,117.000000,4.100000,0.405000,91.000000,19.950000,3.480000,9.000000,0.000000
75%,112500.250000,1.083026e+07,12.310000,1.067000,149.000000,4.410000,0.526000,135.000000,25.430000,4.690000,11.000000,0.000000
max,150000.000000,8.206754e+07,45.000000,1.550000,285.000000,5.000000,0.990000,179.000000,54.060000,10.000000,23.000000,0.800000

Total data pada dataset: (150000, 15) [baris, kolom]

In [4]:
# Menghapus Duplikasi (Removing Duplicates)
print(f'Total baris duplikat: {df.duplicated().sum()}')
df.drop_duplicates()

print(f'Total baris setelah menghapus duplikat: {df.duplicated().sum()}')

df.head(10)

Total baris duplikat: 0
Total baris setelah menghapus duplikat: 0

,ID,Monthly_Revenue,Net_Profit_Margin (%),Burn_Rate_Ratio,Transaction_Count,Avg_Historical_Rating,Review_Text,Review_Volatility,Business_Tenure_Months,Repeat_Order_Rate (%),Digital_Adoption_Score,Peak_Hour_Latency,Location_Competitiveness,Sentiment_Score,Class
0,1,6680716,22.72,0.811,161,4.75,"Transaksi digital lancar, proses checkout tida...",0.313,105,19.40,4.24,Low,9,-0.25,Growth
1,2,5819101,4.46,0.968,104,4.21,"Harga dan kualitas seimbang, pengalaman biasa ...",0.632,95,14.87,1.27,Med,10,0.00,Growth
2,3,5236404,-10.12,1.047,102,3.51,"Pelayanan standar, masih bisa ditingkatkan.",0.470,17,21.00,3.37,Med,8,0.00,Struggling
3,4,8043552,0.04,0.969,99,4.33,"Transaksi digital lancar, proses checkout tida...",0.206,109,30.62,5.41,Low,13,-0.25,Growth
4,5,6071256,4.22,0.954,115,4.34,Selalu repeat order karena kualitasnya terjaga...,0.232,74,20.87,2.67,Low,7,0.25,Growth
5,6,6683141,29.68,0.727,108,4.54,"Pengiriman cepat, admin komunikatif. Culpa ver...",0.185,23,26.35,5.59,Low,16,0.55,Elite
6,7,14123932,15.28,0.860,167,4.54,"Produk cukup baik, kadang waktu tunggu agak la...",0.434,105,22.15,3.95,Med,6,0.00,Growth
7,8,8483571,8.51,0.862,180,4.83,Selalu repeat order karena kualitasnya terjaga.,0.346,124,23.17,7.59,Low,10,0.25,Growth
8,9,14900709,6.00,0.908,135,4.86,Selalu repeat order karena kualitasnya terjaga...,0.285,77,15.85,6.56,Low,7,0.25,Growth
9,10,9232562,-13.64,1.085,89,4.39,"Transaksi digital lancar, proses checkout tida...",0.182,90,17.30,3.22,Low,9,-0.25,Struggling

In [5]:
# Menangani Nilai Hilang (Missing Value)
print(f'Jumlah data yang hilang pada dataset:\n{df.isnull().sum()} \n')

df.head(10)

Jumlah data yang hilang pada dataset:
ID                          0
Monthly_Revenue             0
Net_Profit_Margin (%)       0
Burn_Rate_Ratio             0
Transaction_Count           0
Avg_Historical_Rating       0
Review_Text                 0
Review_Volatility           0
Business_Tenure_Months      0
Repeat_Order_Rate (%)       0
Digital_Adoption_Score      0
Peak_Hour_Latency           0
Location_Competitiveness    0
Sentiment_Score             0
Class                       0
dtype: int64

,ID,Monthly_Revenue,Net_Profit_Margin (%),Burn_Rate_Ratio,Transaction_Count,Avg_Historical_Rating,Review_Text,Review_Volatility,Business_Tenure_Months,Repeat_Order_Rate (%),Digital_Adoption_Score,Peak_Hour_Latency,Location_Competitiveness,Sentiment_Score,Class
0,1,6680716,22.72,0.811,161,4.75,"Transaksi digital lancar, proses checkout tida...",0.313,105,19.40,4.24,Low,9,-0.25,Growth
1,2,5819101,4.46,0.968,104,4.21,"Harga dan kualitas seimbang, pengalaman biasa ...",0.632,95,14.87,1.27,Med,10,0.00,Growth
2,3,5236404,-10.12,1.047,102,3.51,"Pelayanan standar, masih bisa ditingkatkan.",0.470,17,21.00,3.37,Med,8,0.00,Struggling
3,4,8043552,0.04,0.969,99,4.33,"Transaksi digital lancar, proses checkout tida...",0.206,109,30.62,5.41,Low,13,-0.25,Growth
4,5,6071256,4.22,0.954,115,4.34,Selalu repeat order karena kualitasnya terjaga...,0.232,74,20.87,2.67,Low,7,0.25,Growth
5,6,6683141,29.68,0.727,108,4.54,"Pengiriman cepat, admin komunikatif. Culpa ver...",0.185,23,26.35,5.59,Low,16,0.55,Elite
6,7,14123932,15.28,0.860,167,4.54,"Produk cukup baik, kadang waktu tunggu agak la...",0.434,105,22.15,3.95,Med,6,0.00,Growth
7,8,8483571,8.51,0.862,180,4.83,Selalu repeat order karena kualitasnya terjaga.,0.346,124,23.17,7.59,Low,10,0.25,Growth
8,9,14900709,6.00,0.908,135,4.86,Selalu repeat order karena kualitasnya terjaga...,0.285,77,15.85,6.56,Low,7,0.25,Growth
9,10,9232562,-13.64,1.085,89,4.39,"Transaksi digital lancar, proses checkout tida...",0.182,90,17.30,3.22,Low,9,-0.25,Struggling

In [6]:
# Standarisasi (Standardization)
print(f'Kombinasi latensi jam sibuk pada dataset UMKM: {df['Peak_Hour_Latency'].unique()}')
print(f'Kombinasi jenis kelas pada dataset UMKM: {df['Class'].unique()}')



df.head()

Kombinasi latensi jam sibuk pada dataset UMKM: ['Low' 'Med' 'High']
Kombinasi jenis kelas pada dataset UMKM: ['Growth' 'Struggling' 'Elite' 'Critical']

,ID,Monthly_Revenue,Net_Profit_Margin (%),Burn_Rate_Ratio,Transaction_Count,Avg_Historical_Rating,Review_Text,Review_Volatility,Business_Tenure_Months,Repeat_Order_Rate (%),Digital_Adoption_Score,Peak_Hour_Latency,Location_Competitiveness,Sentiment_Score,Class
0,1,6680716,22.72,0.811,161,4.75,"Transaksi digital lancar, proses checkout tida...",0.313,105,19.40,4.24,Low,9,-0.25,Growth
1,2,5819101,4.46,0.968,104,4.21,"Harga dan kualitas seimbang, pengalaman biasa ...",0.632,95,14.87,1.27,Med,10,0.00,Growth
2,3,5236404,-10.12,1.047,102,3.51,"Pelayanan standar, masih bisa ditingkatkan.",0.470,17,21.00,3.37,Med,8,0.00,Struggling
3,4,8043552,0.04,0.969,99,4.33,"Transaksi digital lancar, proses checkout tida...",0.206,109,30.62,5.41,Low,13,-0.25,Growth
4,5,6071256,4.22,0.954,115,4.34,Selalu repeat order karena kualitasnya terjaga...,0.232,74,20.87,2.67,Low,7,0.25,Growth