In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_raw/Airbnb_Cleaned_Europe_Dataset.csv', sep=',')
df.columns = df.columns.str.strip() # Menghapus whitespaces pada kolom/header tabel (jika ada)

# Mengecek jumlah baris apakah terdapat duplikat atau tidak sebelum proses cleaning
print(f'Total baris duplikat: {df.duplicated().sum()}')

Total baris duplikat: 0

In [3]:
# Mengubah Format 
# Mengubah Format Jumlah Desimal 
df['Price'] = df['Price'].round(2)
df['City Center (km)'] = df['City Center (km)'].round(2)
df['Metro Distance (km)'] = df['Metro Distance (km)'].round(2)
df['Attraction Index'] = df['Attraction Index'].round(2)
df['Normalised Attraction Index'] = df['Normalised Attraction Index'].round(2)
df['Restraunt Index'] = df['Restraunt Index'].round(2)
df['Normalised Restraunt Index'] = df['Normalised Restraunt Index'].round(2)

# Mengubah Tipe Data 
df['Person Capacity'] = df['Person Capacity'].astype(int)
df['Cleanliness Rating'] = df['Cleanliness Rating'].astype(int)
df['Guest Satisfaction'] =df['Guest Satisfaction'].astype(int)

# Mengubah Setiap Kata menjadi Huruf Kapital
df['Room Type'] = df['Room Type'].str.title()

df.head()

,City,Price,Day,Room Type,Shared Room,Private Room,Person Capacity,Superhost,Multiple Rooms,Business,Cleanliness Rating,Guest Satisfaction,Bedrooms,City Center (km),Metro Distance (km),Attraction Index,Normalised Attraction Index,Restraunt Index,Normalised Restraunt Index
0,Amsterdam,194.03,Weekday,Private Room,False,True,2,False,1,0,10,93,1,5.02,2.54,78.69,4.17,98.25,6.85
1,Amsterdam,344.25,Weekday,Private Room,False,True,4,False,0,0,8,85,1,0.49,0.24,631.18,33.42,837.28,58.34
2,Amsterdam,264.10,Weekday,Private Room,False,True,2,False,0,1,9,87,1,5.75,3.65,75.28,3.99,95.39,6.65
3,Amsterdam,433.53,Weekday,Private Room,False,True,4,False,0,1,9,90,2,0.38,0.44,493.27,26.12,875.03,60.97
4,Amsterdam,485.55,Weekday,Private Room,False,True,2,True,0,0,10,98,1,0.54,0.32,552.83,29.27,815.31,56.81

In [4]:
# Pengecekan Logika
# Pengecekan Konsistensi Tipe Kamar
df['Shared Room'] = df['Room Type'] == 'Shared Room'
df['Private Room'] = df['Room Type'] == 'Private Room'

# Pengecekan Batas Maksimal Rating
df['Cleanliness Rating'] = df['Cleanliness Rating'].clip(lower=0, upper=10)
df['Guest Satisfaction'] = df['Guest Satisfaction'].clip(lower=0, upper=100)

df.head()

,City,Price,Day,Room Type,Shared Room,Private Room,Person Capacity,Superhost,Multiple Rooms,Business,Cleanliness Rating,Guest Satisfaction,Bedrooms,City Center (km),Metro Distance (km),Attraction Index,Normalised Attraction Index,Restraunt Index,Normalised Restraunt Index
0,Amsterdam,194.03,Weekday,Private Room,False,True,2,False,1,0,10,93,1,5.02,2.54,78.69,4.17,98.25,6.85
1,Amsterdam,344.25,Weekday,Private Room,False,True,4,False,0,0,8,85,1,0.49,0.24,631.18,33.42,837.28,58.34
2,Amsterdam,264.10,Weekday,Private Room,False,True,2,False,0,1,9,87,1,5.75,3.65,75.28,3.99,95.39,6.65
3,Amsterdam,433.53,Weekday,Private Room,False,True,4,False,0,1,9,90,2,0.38,0.44,493.27,26.12,875.03,60.97
4,Amsterdam,485.55,Weekday,Private Room,False,True,2,True,0,0,10,98,1,0.54,0.32,552.83,29.27,815.31,56.81

In [ ]:
# Mengecek jumlah duplikat setelah dibulatkan
print(f'Duplikat setelah proses cleaning: {df.duplicated().sum()}')

# Menghapus baris yang terduplikasi
df.drop_duplicates(inplace=True)

# Pengecekan, apakah terdapat nilai yang masih tidak sesuai (contoh nilai minus)
df.describe()

In [ ]:
df.to_csv('data_clean/clean_airbnb_data.csv', index=False)