In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_raw/DataCoSupplyChainDataset.csv', encoding='latin1')
df.columns = df.columns.str.strip()

In [3]:
# Mengecek Duplikat, Jumlah Data pada Dataset, dan Info
print(f'Total baris duplikat: {df.duplicated().sum()}')
df.drop_duplicates(inplace=True)
print(f'Total baris setelah menghapus duplikat: {df.duplicated().sum()}')

print(f'Total data pada dataset Attendance: {df.shape} [baris, kolom]')

df.info()

Total baris duplikat: 0
Total baris setelah menghapus duplikat: 0
Total data pada dataset Attendance: (180519, 53) [baris, kolom]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [4]:
# Data Cleaning
# Bagian; Customer Country, Costumer State, Customer City, Customer Segment
state_mapping = {
    'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona', 'CA': 'California', 
    'CO': 'Colorado', 'CT': 'Connecticut', 'DC': 'District of Columbia', 
    'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 
    'IA': 'Iowa', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 
    'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 'MA': 'Massachusetts', 
    'MD': 'Maryland', 'MI': 'Michigan', 'MN': 'Minnesota', 'MO': 'Missouri', 
    'MT': 'Montana', 'NC': 'North Carolina', 'ND': 'North Dakota', 
    'NJ': 'New Jersey', 'NM': 'New Mexico', 'NV': 'Nevada', 'NY': 'New York', 
    'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania', 
    'PR': 'Puerto Rico', 'RI': 'Rhode Island', 'SC': 'South Carolina', 
    'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VA': 'Virginia', 
    'WA': 'Washington', 'WI': 'Wisconsin', 'WV': 'West Virginia',
    
    # Memperbaiki data yang salah berdasarkan kodepos
    '91732': 'California', # Zip code untuk area El Monte, CA
    '95758': 'California'  # Zip code untuk area Elk Grove, CA
}

customer_city_fixes = {
    # --- Puerto Rico (Memperbaiki Aksen Spanyol) ---
    'Bayamon': 'Bayamón',
    'Canovanas': 'Canóvanas',
    'Juana Diaz': 'Juana Díaz',
    'Manati': 'Manatí',
    'Mayaguez': 'Mayagüez',
    'San Sebastian': 'San Sebastián',
    
    # --- Amerika Serikat (Memperbaiki Tanda Baca) ---
    'O Fallon': "O'Fallon",
    'Opa Locka': 'Opa-locka',
    'Wilkes Barre': 'Wilkes-Barre',
    'Fond Du Lac': 'Fond du Lac'
}

df['Customer Country'] = df['Customer Country'].replace({'EE. UU.': 'United States of America'})

df['Customer State'] = df['Customer State'].map(state_mapping).fillna(df['Customer State'])

df['Customer City'] = df['Customer City'].astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()
df['Customer City'] = df['Customer City'].replace(customer_city_fixes)
df['Customer City'] = df['Customer City'].replace({'CA': 'Unknown City'})

print("Nama negara pada dataset: ")
print(sorted(df['Customer Country'].unique()))

print("Daftar nama negara bagian Amerika Serikat pada dataset: ")
print(sorted(df['Customer State'].unique()))

print("Daftar nama kota pada dataset: ")
print(sorted(df['Customer City'].unique()))

print("Jenis Customer pada dataset: ")
print(sorted(df['Customer Segment'].unique()))

df.head(10)

Nama negara pada dataset:
['Puerto Rico', 'United States of America']
Daftar nama negara bagian Amerika Serikat pada dataset:
['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Missouri', 'Montana', 'Nevada', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'Tennessee', 'Texas', 'Utah', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin']
Daftar nama kota pada dataset:
['Aguadilla', 'Alameda', 'Albany', 'Albuquerque', 'Algonquin', 'Alhambra', 'Allentown', 'Alpharetta', 'Amarillo', 'Anaheim', 'Ann Arbor', 'Annandale', 'Annapolis', 'Antioch', 'Apex', 'Apopka', 'Arecibo', 'Arlington', 'Arlington Heights', 'Asheboro', 'Astoria', 'Atlanta', 'Augusta', 'Aurora', 'Austin', 'Azusa', 'Bakersfield', 'Baldwin Park', 'Ballwin', 'Baltimore', 'Bartlett', 'Bay Shore', 'Bayamón', 'Bayonne', 'Baytown', 'Beaverton', 'Bell Gardens', 'Bellflower', 'Bellingham', 'Beloit', 'Bend', 'Bensalem', 'Berwyn', 'Billings', 'Birmingham', 'Bismarck', 'Blacksburg', 'Bloomfield', 'Bolingbrook', 'Bountiful', 'Bowling Green', 'Brandon', 'Brentwood', 'Bridgeton', 'Brighton', 'Bristol', 'Brockton', 'Broken Arrow', 'Bronx', 'Brooklyn', 'Broomfield', 'Brownsville', 'Buena Park', 'Buffalo', 'Burnsville', 'Caguas', 'Campbell', 'Canoga Park', 'Canton', 'Canyon Country', 'Canóvanas', 'Carlisle', 'Carlsbad', 'Carmichael', 'Carol Stream', 'Carolina', 'Carrollton', 'Carson', 'Cary', 'Catonsville', 'Cayey', 'Cerritos', 'Chambersburg', 'Chandler', 'Chapel Hill', 'Charlotte', 'Chesapeake', 'Chicago', 'Chicago Heights', 'Chillicothe', 'Chino', 'Chino Hills', 'Chula Vista', 'Cicero', 'Cincinnati', 'Citrus Heights', 'Clarksville', 'Clearfield', 'Clementon', 'Cleveland', 'Clovis', 'College Station', 'Colorado Springs', 'Colton', 'Columbia', 'Columbus', 'Compton', 'Conway', 'Cordova', 'Corona', 'Costa Mesa', 'Crown Point', 'Crystal Lake', 'Cumberland', 'Cupertino', 'Cypress', 'Dallas', 'Daly City', 'Danbury', 'Davis', 'Dayton', 'Dearborn', 'Decatur', 'Del Rio', 'Denton', 'Denver', 'Des Plaines', 'Detroit', 'Diamond Bar', 'Dorchester Center', 'Douglasville', 'Doylestown', 'Dubuque', 'Duluth', 'Dundalk', 'Eagle Pass', 'East Brunswick', 'East Lansing', 'Edinburg', 'Edison', 'El Cajon', 'El Centro', 'El Monte', 'El Paso', 'Elgin', 'Elk Grove', 'Elmhurst', 'Elyria', 'Encinitas', 'Endicott', 'Enfield', 'Englewood', 'Escondido', 'Eugene', 'Everett', 'Ewa Beach', 'Fairfield', 'Far Rockaway', 'Fargo', 'Fayetteville', 'Federal Way', 'Findlay', 'Florissant', 'Flushing', 'Folsom', 'Fond du Lac', 'Fontana', 'Forest Hills', 'Fort Lauderdale', 'Fort Washington', 'Fort Worth', 'Fountain Valley', 'Frankfort', 'Freehold', 'Freeport', 'Fremont', 'Fresno', 'Fullerton', 'Gaithersburg', 'Garden Grove', 'Gardena', 'Garland', 'Germantown', 'Gilroy', 'Glen Burnie', 'Glendale', 'Glenview', 'Goleta', 'Goose Creek', 'Granada Hills', 'Grand Prairie', 'Granite City', 'Greeley', 'Greensboro', 'Greensburg', 'Greenville', 'Grove City', 'Guayama', 'Guaynabo', 'Gwynn Oak', 'Hacienda Heights', 'Hagerstown', 'Hamilton', 'Hampton', 'Hamtramck', 'Hanford', 'Hanover', 'Harlingen', 'Harvey', 'Hawthorne', 'Hayward', 'Hempstead', 'Henderson', 'Hendersonville', 'Henrico', 'Hesperia', 'Hialeah', 'Hickory', 'Highland', 'Highland Park', 'Hilliard', 'Holland', 'Hollister', 'Hollywood', 'Honolulu', 'Houston', 'Howell', 'Humacao', 'Huntington Beach', 'Huntington Park', 'Huntington Station', 'Hyattsville', 'Indianapolis', 'Indio', 'Irving', 'Irvington', 'Irwin', 'Ithaca', 'Jackson', 'Jackson Heights', 'Jacksonville', 'Jamaica', 'Jersey City', 'Joliet', 'Jonesboro', 'Juana Díaz', 'Kailua', 'Kaneohe', 'Katy', 'Kenner', 'Kent', 'Knoxville', 'La Crosse', 'La Habra', 'La Mesa', 'La Mirada', 'La Puente', 'Laguna Hills', 'Laguna Niguel', 'Lake Forest', 'Lakewood', 'Lancaster', 'Lansdale', 'Laredo', 'Las Cruces', 'Las Vegas', 'Lawrence', 'Lawrenceville', 'Lawton', 'Lenoir', 'Levittown', 'Lewisville', 'Lilburn', 'Lindenhurst', 'Lithonia', 'Littleton', 'Livermore', 'Lockport', 'Lodi', 'Lombard', 'Lompoc', 'Long Beach', 'Longmont', 'Longview', 'Los Angeles', 'Louisville', 'Loveland', 'Lutz', 'Lynn', 'Lynnwood', 'Lynwood', 'Madera', 'Madison', 'Malden', 'Manatí', 'Manchester', 'Marietta', 'Marion', 'Marrero', 'Martinez', 'Martinsburg', 'Massapequa', 'Massillon', 'Mayagüez', 'Mcallen', 'Mchenry', 'Mechanicsburg', 'Medford', 'Medina', 'Memphis', 'Mentor', 'Merced', 'Meridian', 'Mesa', 'Mesquite', 'Metairie', 'Methuen', 'Miami', 'Michigan City', 'Middletown', 'Milford', 'Mililani', 'Milpitas', 'Milwaukee', 'Mission', 'Mission Viejo', 'Modesto', 'Moline', 'Montebello', 'Moreno Valley', 'Morganton', 'Morristown', 'Morrisville', 'Mount Pleasant', 'Mount Prospect', 'Murfreesboro', 'Muskegon', 'Napa', 'Nashville', 'National City', 'New Albany', 'New Bedford', 'New Braunfels', 'New Brunswick', 'New Castle', 'New Haven', 'New Orleans', 'New York', 'Newark', 'Newburgh', 'Norcross', 'Norfolk', 'Normal', 'North Bergen', 'North Hills', 'North Hollywood', 'North Las Vegas', 'North Richland Hills', 'North Tonawanda', 'Norwalk', "O'Fallon", 'Oak Lawn', 'Oakland', 'Oceanside', 'Ogden', 'Olathe', 'Ontario', 'Opa-locka', 'Opelousas', 'Orange Park', 'Oregon City', 'Orlando', 'Oviedo', 'Oxnard', 'Pacoima', 'Painesville', 'Palatine', 'Palmdale', 'Palo Alto', 'Panorama City', 'Paramount', 'Parkville', 'Pasadena', 'Passaic', 'Pawtucket', 'Peabody', 'Pekin', 'Peoria', 'Perth Amboy', 'Pharr', 'Philadelphia', 'Phoenix', 'Pico Rivera', 'Piscataway', 'Pittsburg', 'Pittsfield', 'Placentia', 'Plainfield', 'Plano', 'Plymouth', 'Pomona', 'Pompano Beach', 'Ponce', 'Porterville', 'Portland', 'Potomac', 'Poway', 'Powder Springs', 'Princeton', 'Provo', 'Quincy', 'Raleigh', 'Rancho Cordova', 'Rancho Cucamonga', 'Redmond', 'Rego Park', 'Reno', 'Reseda', 'Revere', 'Reynoldsburg', 'Rialto', 'Richardson', 'Richmond', 'Ridgewood', 'Rio Grande', 'Rio Rancho', 'Riverside', 'Rochester', 'Rock Hill', 'Rome', 'Roseburg', 'Rosemead', 'Roseville', 'Roswell', 'Round Rock', 'Rowland Heights', 'Sacramento', 'Saginaw', 'Saint Charles', 'Saint Louis', 'Saint Paul', 'Saint Peters', 'Salem', 'Salina', 'Salinas', 'Salt Lake City', 'San Antonio', 'San Benito', 'San Bernardino', 'San Diego', 'San Francisco', 'San Jose', 'San Juan', 'San Marcos', 'San Pablo', 'San Pedro', 'San Ramon', 'San Sebastián', 'Sandusky', 'Sanford', 'Santa Ana', 'Santa Clara', 'Santa Cruz', 'Santa Fe', 'Santa Maria', 'Santee', 'Scottsdale', 'Seattle', 'Sheboygan', 'Silver Spring', 'Simi Valley', 'Smyrna', 'South El Monte', 'South Gate', 'South Ozone Park', 'South Richmond Hill', 'South San Francisco', 'Spokane', 'Spring', 'Spring Valley', 'Springfield', 'Stafford', 'Stamford', 'Staten Island', 'Stockbridge', 'Stockton', 'Stone Mountain', 'Strongsville', 'Sugar Land', 'Summerville', 'Sumner', 'Sun Valley', 'Sunnyvale', 'Sylmar', 'Tallahassee', 'Tampa', 'Taunton', 'Taylor', 'Temecula', 'Tempe', 'Tinley Park', 'Toa Alta', 'Toa Baja', 'Toms River', 'Tonawanda', 'Tracy', 'Troy', 'Trujillo Alto', 'Tucson', 'Tulare', 'Tustin', 'Union', 'Union City', 'Unknown City', 'Upland', 'Vacaville', 'Vallejo', 'Valrico', 'Van Nuys', 'Vega Baja', 'Ventura', 'Victorville', 'Virginia Beach', 'Visalia', 'Vista', 'Waipahu', 'Walnut', 'Warren', 'Washington', 'Watsonville', 'Waukegan', 'Wayne', 'Webster', 'Weslaco', 'West Chester', 'West Covina', 'West Haven', 'West Jordan', 'West Lafayette', 'West New York', 'West Orange', 'Westerville', 'Westland', 'Westminster', 'Wheaton', 'Wheeling', 'Wichita', 'Wilkes-Barre', 'Williamsport', 'Wilmington', 'Winnetka', 'Winter Park', 'Woodbridge', 'Woodside', 'Woonsocket', 'Wyandotte', 'Wyoming', 'Yauco', 'Yonkers', 'York', 'Ypsilanti', 'Yuma', 'Zanesville']
Jenis Customer pada dataset:
['Consumer', 'Corporate', 'Home Office']

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [5]:
# Data Cleaning
# Order Country, Order Region, Order City, Market

order_state_fixes = {
    # =========================================================
    # AMERICA (NORTH, CENTRAL, SOUTH)
    # =========================================================

    # --- North America ---
    # === Canada ===
    'Columbia brit nica': 'British Columbia',
    'Nueva Escocia': 'Nova Scotia',
    
    # === United States of America ===
    'Nueva York': 'New York',
    'Nueva Jersey': 'New Jersey',
    'Nuevo Hampshire': 'New Hampshire',
    'Nuevo México': 'New Mexico',
    'Nuevo M xico': 'New Mexico',
    'Carolina del Norte': 'North Carolina',
    'Carolina del Sur': 'South Carolina',
    'Dakota del Norte': 'North Dakota',
    'Dakota del Sur': 'South Dakota',
    'Distrito de Columbia': 'District of Columbia',
    'Virginia Occidental': 'West Virginia',
    'Columbia Británica': 'British Columbia',
    'Nueva Escocia': 'Nova Scotia',
    'Oreg n': 'Oregon',
    'Pensilvania': 'Pennsylvania',
    'Misisipi': 'Mississippi', 
    'Misuri': 'Missouri',
    'Luisiana': 'Louisiana',
    'Terranova': 'Newfoundland and Labrador',

    # --- Central America & Caribbean ---
    # === Mexico ===
    'Nuevo Le n': 'Nuevo León',
    'M xico': 'México',
    'Michoac n': 'Michoacán',
    'Yucat n': 'Yucatán',
    'Quer taro': 'Querétaro',
    'San Luis Potos': 'San Luis Potosí',

    # === El Salvador ===
    'Cuscatl n': 'Cuscatlán',

    # === Belize ===
    'Distrito de Cayo': 'Cayo District',
    
    # === Dominican Republic ===
    'Monse or Nouel': 'Monseñor Nouel',
    'San Pedro de Macoris': 'San Pedro de Macorís',
    'San Pedro de Macor s': 'San Pedro de Macorís',

    # === Honduras ===
    'Francisco Moraz n': 'Francisco Morazán', # Department
    'Cort s': 'Cortés',
    'Col n': 'Colón',
    'Atl ntida': 'Atlántida',

    # === Panama === 
    'Col n': 'Colón',
    'Chiriqu': 'Chiriquí', 
    'Panam': 'Panama',
    
    # === Cuba ===
    'Holgu n': 'Holguín',
    'Pinar del R o': 'Pinar del Río',
    'Camag ey': 'Camagüey',
    'Ciego de vila': 'Ciego de Ávila',
    'Sancti Sp ritus': 'Sancti Spíritus',
    'Guant namo': 'Guantánamo',
    'Santiago de Cuba': 'Santiago de Cuba',

    # === Nicaragua ===
    'Estel': 'Estelí',

    # --- South American ---
    # === Colombia === 
    'Antioqu a': 'Antioquia',
    'Quind o': 'Quindío',
    'Nari o': 'Nariño',
    'Atl ntico': 'Atlántico',
    'Bogot': 'Bogotá',
    'Boyac': 'Boyacá',
    'Caquet': 'Caquetá', 
    'Choc': 'Chocó',
    'Departamento Atl ntico': 'Atlántico',
    'Norte de Santander': 'North Santander',
    'Valle del Cauca': 'Valle del Cauca',

    # === Ecuador === 
    'Los R os': 'Los Ríos', 
    'Manab': 'Manabí',
    
    # === Venezuela ===
    'Anzo tegui': 'Anzoátegui',
    'Bol var': 'Bolívar',
    'M rida': 'Mérida',
    'T chira': 'Táchira',
    'Regi n Capital': 'Capital Region',
    'Gu rico': 'Guárico',
    'San Crist bal': 'San Cristóbal',
    'Nueva Esparta': 'Nueva Esparta',

    # === Bolivia ===
    'Potos': 'Potosí',

    # === French Guiana ===
    'Demerara-Berbice Superior': 'Upper Demerara-Berbice',
    'Franz sisch-Guayana': 'French Guiana',
    
    # === Brazil ===
    'Bah a': 'Bahía',
    'Goi s': 'Goiás',
    'Amap': 'Amapá',
    'Mara n': 'Maranhão',
    'Río de Janeiro': 'Rio de Janeiro',
    'R o de Janeiro': 'Rio de Janeiro',
    'Río Grande del Norte': 'Rio Grande do Norte',
    'R o Grande del Norte': 'Rio Grande do Norte',
    'Mato Grosso del Sur': 'Mato Grosso do Sul',
    'S o Paulo': 'São Paulo',
    'Esp ritu Santo': 'Espírito Santo',
    'Para ba': 'Paraíba',
    'Cear': 'Ceará',
    'Par': 'Pará',
    'Paran': 'Paraná',
    'Piau': 'Piauí',
    'Rond nia': 'Rondônia',
    
    # === Paraguay ===
    'Asunci n': 'Asunción',

    # === Uruguay === 
    'Paysand': 'Paysandú',

    # === Chile ===
    'B o-B o': 'Bío-Bío',
    'Magallanes y Ant rtica Chilena': 'Magallanes and Chilean Antarctica',
    'Valpara so': 'Valparaíso',
    'Santiago de Chile': 'Santiago',
    'Tarapac': 'Tarapacá',

    # === Peru ===
    'Jun n': 'Junín',
    'Lima (ciudad)': 'Lima',
    'Mara n': 'Marañón',
    
    # === Argentina ===
    'C rdoba': 'Córdoba',
    'Neuqu n': 'Neuquén',
    'Entre R os': 'Entre Ríos',
    'R os': 'Río Tala',
    'Río Negro': 'Rio Negro',
    'R o Negro': 'Rio Negro',
    'Santiago del Estero': 'Santiago del Estero',
    'Buenos Aires (provincia)': 'Buenos Aires',

    # =========================================================
    # EUROPEAN
    # =========================================================

    # === Portugal === 
    'Set bal': 'Setúbal',

    # === Spain ===
    'Catalu a': 'Catalonia',
    'Cataluña': 'Catalonia',
    'Andaluc a': 'Andalusia',
    'Andalucía': 'Andalusia',
    'Le n': 'León',
    'Castilla y Le n': 'Castile and León',
    'Castilla and León': 'Castile and León',
    'Islas Baleares': 'Illes Balears',
    'Pa s Vasco': 'Basque Country',
    
    # === Ireland ===
    'Dubl n': 'Dublin',
    'Dubl n del Sur': 'South Dublin',

    # === United Kingdom (UK) ===
    'Gales': 'Wales',
    'Inglaterra': 'England',
    'Escocia': 'Scotland',

    # === Finland === 
    'Finlandia del Sudoeste': 'Southwest Finland',
    
    # === Sweden ===
    'Estocolmo': 'Stockholm',
    'Escania': 'Scania',
    'S dermanland': 'Södermanland',
    'V rmland': 'Värmland',
    'V stra G taland': 'Västra Götaland',
    
    # === France ===
    'Auvernia': 'Auvergne',
    'Auvernia-R dano-Alpes': 'Auvergne-Rhône-Alpes',
    'Alsacia-Champa a-Ardenas-Lorena': 'Grand Est',
    'Aquitania-Lemos n-Poitou-Charentes': 'Nouvelle-Aquitaine',
    'Borgo a-Franco Condado': 'Bourgogne-Franche-Comté',
    'Borgoña-Franco Condado': 'Bourgogne-Franche-Comté',
    'Breta a': 'Brittany',
    'Bretaña': 'Brittany',
    'Centro-Valle de Loira': 'Centre-Val de Loire',
    'Norte-Paso de Calais-Picard a': 'Hauts-de-France',
    'Normand a': 'Normandy',
    'Normandía': 'Normandy',
    'Isla de Francia': 'Île-de-France',
    'Pa ses del Loira': 'Pays de la Loire',
    'Países del Loira': 'Pays de la Loire',
    'Provenza-Alpes-Costa Azul': "Provence-Alpes-Côte d'Azur",
    'Corse': 'Corsica',
    'Languedoc-Rosell n-Mediod a-Pirineos': 'Occitanie',
    'Guadalupe': 'Guadeloupe',           
    'Martinica': 'Martinique',

    # === Belgium ===
    'Flanders Occidental': 'West Flanders',
    'Flanders Oriental': 'East Flanders',
    'Amberes': 'Antwerp',
    'Bruselas': 'Brussels',
    'Brabante Flamenco': 'Flemish Brabant',
    'Lieja': 'Liège',
    'Henao': 'Hainaut',

    # === Netherlands ===
    'Holanda Meridional': 'South Holland',
    'Holanda Septentrional': 'Noord-Holland',
    'G eldres': 'Gelderland',
    'Brabante Septentrional': 'North Brabant',
    'Frisia': 'Friesland',
    'Limburgo': 'Limburg',

    # === Luxembourg === 
    'Luxemburgo': 'Luxembourg',

    # === Switzerland ===
    'Zúrich': 'Zürich',
    'Z rich': 'Zürich',
    'Basilea-Ciudad': 'Basel-Stadt',
    'Berna': 'Bern',
    'Ginebra': 'Geneva',
    'Lucerna': 'Lucerne',
    'San Galo': 'St. Gallen',
    
    # === Italy ===
    'Lombard a': 'Lombardy',
    'Emilia-Roma a': 'Emilia-Romagna',
    'Cerde a': 'Sardinia',
    'Umbr a': 'Umbria',
    'Abruzos': 'Abruzzo',
    'Lacio': 'Lazio',
    'Piamonte': 'Piedmont',
    'V neto': 'Veneto',
    
    # === Denmark ===
    'Dinamarca Meridional': 'Region of Southern Denmark',
    'Zelanda': 'Zealand',
    'Selandia': 'Zealand',
    'Jutlandia Central': 'Central Denmark Region',

    # === Germany ===
    'Baden-Wurtemberg': 'Baden-Württemberg',
    'Baja Sajonia': 'Lower Saxony',
    'Berl n': 'Berlin',
    'Bavaria': 'Bavaria',
    'Brandenburgo': 'Brandenburg',
    'Hamburgo': 'Hamburg',
    'Sajonia': 'Saxony',
    'Sajonia-Anhalt': 'Saxony-Anhalt',
    'Turingia': 'Thuringia',
    'Renania-Palatinado': 'Rheinland-Pfalz',
    'Renania del Norte-Westfalia': 'North Rhine-Westphalia',
    'Mecklemburgo-Pomerania Occidental': 'Mecklenburg-Vorpommern',

    # === Poland ===
    'Gran Polonia': 'Greater Poland',
    'Polonia Menor': 'Lesser Poland',
    'Podlaquia': 'Podlaskie',

    # === Austria ===
    'Alta Austria': 'Upper Austria',
    'Carintia': 'Carinthia',
    'Salzburgo': 'Salzburg',
    'Stiria': 'Styria',
    'Viena': 'Vienna',

    # === Czechia ===
    'Hradec Kr lov': 'Hradec Králové',
    'st nad Labem': 'Ústí nad Labem',
    'Pilsen': 'Plzeň',
    'Praga': 'Prague',
    
    # === Slovakia ===
    'Bansk Bystrica': 'Banská Bystrica',
    'ilina': 'Žilina',
    'Bansk Bystrica': 'Banská Bystrica',

    # === Slovenia ===
    'Liubliana': 'Ljubljana',
    
    # === Hungary ===
    'B k s': 'Békés',
    'Hajd -Bihar': 'Hajdú-Bihar',
    'Gy?r': 'Győr',

    # === Croatia ===
    'Zagrebacka': 'Zagrebačka',
    'Split-Dalmacia': 'Split-Dalmatia',
    'Osjecko-Baranjska': 'Osijek-Baranja',

    # === Bulgaria ===
    'Sof a-Ciudad': 'Sofia',

    # === Bosnia and Herzegovina ===
    'Federaci n de Bosnia y Herzegovina': 'Federation of Bosnia and Herzegovina',

    # === Albania ===
    'Durr s': 'Durrës',
    'Shkod r': 'Shkodër',
    'Vlor': 'Vlorë',

    # === Lithuania ===
    'Klaip?da': 'Klaipėda',
    'iauliai': 'Šiauliai',
    'Vilna': 'Vilnius',
    
    # === Belarus ===
    'G mel': 'Gomel',
    
    # === Russia ===
    'Arj nguelsk': 'Arkhangelsk',
    'Bashkortost n': 'Bashkortostan',
    'Daguest n': 'Dagestan',
    'Astrac n': 'Astrakhan',
    'B lgorod': 'Belgorod',
    'Cheli binsk': 'Chelyabinsk',
    'N vgorod': 'Novgorod',
    'Vlad mir': 'Vladimir',
    'Vor nezh': 'Voronezh',
    'Mosc': 'Moscow',
    'Kaliningrado': 'Kaliningrad',
    'St vropol': 'Stavropol',
    'Yevrey': 'Jewish Autonomous Oblast',

    # === Georgia === 
    'Tiflis': 'Tbilisi',
    'Imericia': 'Imereti',

    # === Ukraine ===
    'J rkov': 'Kharkiv',
    'Tern pil': 'Ternopil',
    'V nnytsia': 'Vinnytsia',
    'Zhyt myr': 'Zhytomyr',
    'Jers n': 'Kherson',
    'Zaporiyia': 'Zaporizhzhia',
    'Volinia': 'Volyn',

    # === Moldova ===
    'Chisin u': 'Chișinău',
    
    # === Romania ===
    'V lcea': 'Vâlcea',
    'Bra?ov': 'Brașov',
    'Constanza': 'Constanța',

    # =========================================================
    # AFRICA
    # =========================================================

    # === Morocco === 
    'Fez-Bulm n': 'Fès-Boulemane',
    'Fas Bulman': 'Fès-Boulemane',
    'T nger-Tetu n': 'Tangier-Tétouan',
    'Chau a-Uardiga': 'Chaouia-Ouardigha',
    'Garb-Chrarda-Beni Hsen': 'Gharb-Chrarda-Beni Hssen',
    'Rabat-Sal -Zemur-Zaer': 'Rabat-Salé-Zemmour-Zaer',
    'Gran Casablanca': 'Grand Casablanca',
    'Mequinez-Tafilalet': 'Meknès-Tafilalet',
    'Sus-Masa-Draa': 'Souss-Massa-Drâa',
    'Taza-Alhucemas-Taunat': 'Taza-Al Hoceima-Taounate',

    # === Western Sahara ===
    'El Aai n': 'El Aaiún',
    
    # === Algeria ===
    'Or n': 'Oran',                  
    'Bug a': 'Bejaia',
    'B char': 'Béchar',
    'Constantina': 'Constantine',

    # === Tunisia ===
    'T nez': 'Tunis',

    # === Libya ===
    'Bengasi': 'Benghazi',

    # === Egypt ===
    'Alejandr a': 'Alexandria',
    'Alejandría': 'Alexandria',
    'Fay n': 'Al Fayyum',                
    'Puerto Sa d': 'Port Said',
    'Bursaid': 'Port Said',
    'El Cairo': 'Cairo',
    'Mar Rojo': 'Red Sea Governorate',
    'Kafr el Sheij': 'Kafr el-Sheikh',

    # === Benin ===
    'Ou m': 'Ouémé',

    # === Angola ===
    'Bi': 'Bié',

    # === Burundi ===
    'Buyumbura Mairie': 'Bujumbura Mairie',

    # === Côte d'Ivoire ===
    'Vall e du Bandama': 'Vallée du Bandama',

    # === Djibouti ===
    'Yibuti': 'Djibouti',

    # Ghana
    'Gran Accra': 'Greater Accra',

    # === Guinea ===
    'Nz r kor': 'Nzérékoré',

    # === Guinea-Bissau ===
    'Bis u': 'Bissau',

    # === Niger === 
    'N ger': 'Niger',

    # === Sudan ===
    'Jartum': 'Khartoum',
    'Nilo Blanco': 'White Nile',

    # === South Sudan ===
    'Ecuatoria Central': 'Central Equatoria',

    # === Senegal ===
    'Thi s': 'Thiès',

    # === Democratic Republic of Congo ===
    'quateur': 'Équateur',
    'Bajo Congo': 'Kongo Central',
    'Kasai Occidental': 'Kasai-Occidental',
    'Kasai Oriental': 'Kasai-Oriental',
    'Kivu del Sur': 'South Kivu',
    'Provincia Oriental': 'Orientale Province',
    'quateur': 'Équateur',

    # Togo
    'Mar tima': 'Maritime Region',

    # === Zimbabwe ===
    'Mashonalandia Occidental': 'Mashonaland West',

    # === South Africa ===
    'Cabo Occidental': 'Western Cape', 
    'Cabo Oriental': 'Eastern Cape',
    'Estado Libre': 'Free State',

    # === No General Africa ===
    'Gran Valle del Rift': 'Great Rift Valley',

    # =========================================================
    # ASIA (Central, West, East, South, Southeast)
    # =========================================================

    # Central Asia
    # === Kazakhstan ===
    'Kostan i': 'Kostanay',
    'Ciudad de Almat': 'Almaty',
    'Ciudad de Almaty': 'Almaty',
    'Karagand': 'Karaganda',
    'Astan': 'Astana',

    # === Uzbekistan === 
    'Namang n': 'Namangan',          
    'Andij n': 'Andijan',            
    'Surjandar n': 'Surxondaryo',
    'Kashkadar': 'Qashqadaryo',

    # === Turkmenistan ===
    'Asjabad': 'Ashgabat',

    # West Asia (Middle East)
    # === Turkey ===
    'Bing l': 'Bingöl',
    'D zce': 'Düzce',                
    'K tahya': 'Kütahya',
    'Estambul': 'Istanbul',
    'anakkale': 'Çanakkale',
    'Kahramanmara?': 'Kahramanmaraş',
    'Trebisonda': 'Trabzon',

    # === Azerbaijan === 
    'Baki': 'Baku',

    # === Iran ===
    'Juzest n': 'Khuzestan',          
    'Isfah n': 'Isfahan',            
    'Hamad n': 'Hamedan',            
    'Teher n': 'Tehran',
    'Guil n': 'Gīlān',              
    'Zany n': 'Zanjan',              
    'Sist n y Baluchist n': 'Sistan and Baluchestan',
    'Mazandar n': 'Māzandarān',      
    'Qazv n': 'Qazvin',              
    'Golest n': 'Golestán',          
    'Semn n': 'Semnan',              
    'Hormozg n': 'Hormozgān',
    'Joras n Razav': 'Khorasan Razavi',
    'Joras n del Sur': 'South Khorasan',

    # === Iraq === 
    'N nive': 'Nineveh',
    'Kurdist n': 'Kurdistan',
    'Bagdad': 'Baghdad',
    'Basora': 'Basra',
    'Di Car': 'Dhi Qar',
    'Diala': 'Diyala',
    'Cadisia': 'Al-Qadisiyyah',
    'Saladino': 'Saladin',
    'Mesena': 'Maysan',
    'Babilonia': 'Babil',

    # === Lebanon ===
    'L bano del Norte': 'North Lebanon',

    # === Jordan ===
    'Am n': 'Amman',

    # === Israel === 
    'Jerusal n': 'Jerusalem', 

    # === Saudi Arabian === 
    'Jiz n': 'Jizan',
    'Meca': 'Mecca',
    'Riad': 'Riyadh',

    # United Arab Emirates
    'Ajm n': 'Ajmān',

    # === Oman === 
    'Mascate': 'Muscat',

    # East Asia
    # === Mongolia ===
    'Ulán Bator': 'Ulaanbaatar',     
    'Ul n Bator': 'Ulaanbaatar',
    
    # === China ===
    'Pek n': 'Peking',
    'Pekín': 'Beijing',
    'Peking': 'Beijing',
    'Shangh i': 'Shanghai',
    'Shanghái': 'Shanghai',
    'Mongolia Interior': 'Inner Mongolia',
    
    # === Taiwan ===
    'Taip i': 'Taipei',
    
    # === South Korea ===
    'Se l': 'Seoul',
    'Seúl': 'Seoul',
    'Chungcheong del Sur': 'South Chungcheong',

    # === Japan ===
    'Tokio': 'Tokyo',
    
    # South Asia
    # === Bangladesh ===
    'Daca': 'Dhaka',
    
    # === India ===
    'Rajast n': 'Rajasthan',
    'Bengala Occidental': 'West Bengal',
    'Capital Nacional': 'National Capital Territory',
    'Guyarat': 'Gujarat',
    'Punyab': 'Punjab',
    'Jammu y Cachemira': 'Jammu and Kashmir',
    
    # === Pakistan ===
    'Baluchist n': 'Balochistan', 
    'Jaiber Pajtunju': 'Khyber Pakhtunkhwa',

    # Southeast Asia
    # === Laos === 
    'Prefectura de Vienti n': 'Vientiane',

    # === Cambodia === 
    'Nom Pen': 'Phnom Penh', 
    
    # === Myanmar === 
    'Rang n': 'Yangon',
    'Rangún': 'Yangon',
    
    # === Vietnam ===
    'Ciudad Ho Chi Minh': 'Ho Chi Minh City',
    'D Nang': 'Da Nang',
    'T?nh C?n Th?': 'Can Tho',       
    'Th? D H N?i': 'Hanoi',
    'Kh nh H a': 'Khanh Hoa',
    'Ki n Giang': 'Kiên Giang',
    
    # === Singapore ===
    'Singapur': 'Singapore',

    # === Indonesia ===
    'Yakarta': 'DKI Jakarta',
    'Java Occidental': 'Jawa Barat',
    'Java Central': 'Jawa Tengah',
    'Java Oriental': 'Jawa Timur',
    'C lebes Central': 'Sulawesi Tengah',
    'C lebes Septentrional': 'Sulawesi Utara',
    'C lebes Suroriental': 'Sulawesi Tenggara',
    'Célebes Central': 'Sulawesi Tengah',      
    'Célebes Septentrional': 'Sulawesi Utara',  
    'Célebes Suroriental': 'Sulawesi Tenggara',
    'Sumatra Meridional': 'Sumatera Selatan',      
    'Sumatra Occidental': 'Sumatera Barat',       
    'Sumatra Septentrional': 'Sumatera Utara',   
    'Kalimantan Oriental': 'Kalimantan Timur',   
    'Borneo Occidental': 'Kalimantan Barat',     
    'Borneo Meridional': 'Kalimantan Selatan',    
    'Nusa Tenggara Oriental': 'Nusa Tenggara Timur', 
    'Nusatenggara Occidental': 'Nusa Tenggara Barat',
    
    # === Philippines ===
    'Luzón Central': 'Central Luzon',
    'Luz n Central': 'Central Luzon',
    'Calabarz n': 'Calabarzon',
    'Visayas Occidental': 'Western Visayas',
    'Mindanao Septentrional': 'Northern Mindanao',

    # =========================================================
    # OCEANIA
    # =========================================================
    'Australia Occidental': 'Western Australia',
    'Australia del Sur': 'South Australia',
    'Nueva Gales del Sur': 'New South Wales',
    'Territorio de la Capital Australiana': 'Australian Capital Territory',
    'Territorio del Norte': 'Northern Territory',

    # === Generic ===
    'Territorio de la Capital Federal': 'Federal Capital Territory',
    'Meridional': 'Southern',
    'Septentrional': 'Northern',
    'Occidental': 'Western',
    'Oriental': 'Eastern',
    'Noroeste': 'North West',
    'Sudeste': 'South East',
    'Sud': 'South',
    'Ouest': 'West',
    'Ouest del Sur': 'Southwest',
    'Est': 'East',
}

df['Order State'] = df['Order State'].astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()
df['Order State'] = df['Order State'].replace(order_state_fixes)

print("Daftar state(negara) pesanan pada dataset: ")
print(sorted(df['Order State'].unique()))

print("Daftar region(wilayah) pada dataset: ")
print(sorted(df['Order Region'].unique()))

df.head(10)

Daftar state(negara) pesanan pada dataset:
['Abia', 'Abruzzo', 'Aceh', 'Acre', 'Adamaoua', 'Adamawa', 'Adana', 'Adiyaman', 'Afyonkarahisar', 'Aichi', 'Ajmān', 'Akmola', 'Aksaray', 'Akwa Ibom', 'Al Asimah', 'Al Bahr al Ahmar', 'Al Buhayrah', 'Al Fayyum', 'Al Hudayda', 'Al Jawf', 'Al Marqab', 'Al-Qadisiyyah', 'Alabama', 'Alagoas', 'Alberta', 'Alexandria', 'Alger', 'Alibori', 'Almaty', 'Amapá', 'Amasya', 'Amazonas', 'Amman', 'Amur', 'Analamanga', 'Anambra', 'Ancash', 'Andalusia', 'Andhra Pradesh', 'Andijan', 'Anhui', 'Ankara', 'Annaba', 'Anseba', 'Antalya', 'Antioquia', 'Antofagasta', 'Antwerp', 'Anzoátegui', 'Aomori', 'Apulia', 'Ar Raqa', 'Arad', 'Aragua', 'Arauca', 'Arbil', 'Ardahan', 'Ardebil', 'Arequipa', 'Arges', 'Arica y Parinacota', 'Arizona', 'Arkansas', 'Arkhangelsk', 'Artemisa', 'Artibonito', 'Arusha', 'Ash Sharqiyah', 'Ashanti', 'Ashgabat', 'Asir', 'Asiut', 'Assam', 'Astana', 'Astrakhan', 'Asturias', 'Asunción', 'Aswan', 'Atacama', 'Atakora', 'Atlántico', 'Atlántida', 'Atsimo-Andrefana', 'Atsinanana', 'Attica', 'Auckland', 'Australian Capital Territory', 'Auvergne', 'Auvergne-Rhône-Alpes', 'Aveiro', 'Ayacucho', 'Aydin', 'Azuay', 'Babil', 'Bacau', 'Baden-Württemberg', 'Baghdad', 'Bahía', 'Baja California', 'Baja California Sur', 'Baku', 'Bali', 'Balikesir', 'Balochistan', 'Balti', 'Bamako', 'Bandundu', 'Bangkok', 'Bangui', 'Bani Suwayf', 'Banská Bystrica', 'Barahona', 'Basel-Stadt', 'Bashkortostan', 'Basilicata', 'Basque Country', 'Basra', 'Batman', 'Batna', 'Bauchi', 'Bavaria', 'Bay of Plenty', 'Beirut', 'Bejaia', 'Belgorod', 'Benadir', 'Benghazi', 'Bengkulu', 'Benguela', 'Benue', 'Berlin', 'Bern', 'Bihar', 'Bihor', 'Bingöl', 'Bishkek', 'Bissau', 'Bistrita-Nasaud', 'Bitola', 'Bié', 'Boeny', 'Bogotá', 'Bolu', 'Bolívar', 'Borgou', 'Borno', 'Botosani', 'Bourgogne-Franche-Comté', 'Boyacá', 'Braga', 'Braila', 'Brandenburg', 'Brașov', 'Bremen', 'Brest', 'Briansk', 'British Columbia', 'Brittany', 'Brussels', 'Budapest', 'Buenos Aires', 'Bujumbura Mairie', 'Bulawayo', 'Burgas', 'Bursa', 'Busan', 'Bushehr', 'Buskerud', 'Buzau', 'Béchar', 'Békés', 'Bío-Bío', 'Cabo Delgado', 'Cairo', 'Cajamarca', 'Calabarzon', 'Calabria', 'Caldas', 'California', 'Callao', 'Camagüey', 'Campania', 'Campeche', 'Can Tho', 'Canelones', 'Cantabria', 'Canterbury', 'Capital Region', 'Caquetá', 'Carabobo', 'Caras-Severin', 'Carinthia', 'Casanare', 'Castile and León', 'Castilla-La Mancha', 'Catalonia', 'Catamarca', 'Cayo District', 'Ceará', 'Central', 'Central Denmark Region', 'Central Equatoria', 'Central Luzon', 'Centre-Val de Loire', 'Centro', 'Cesar', 'Ceuta', 'Chaco', 'Chaguanas', 'Chandigarh', 'Chaouia-Ouardigha', 'Chelyabinsk', 'Cherkasy', 'Chernihiv', 'Chhattisgarh', 'Chiapas', 'Chiba', 'Chihuahua', 'Chimaltenango', 'Chinandega', 'Chiriquí', 'Chittagong', 'Chișinău', 'Chocó', 'Choluteca', 'Chongqing', 'Chubut', 'Chukha', 'Chuquisaca', 'Cidade De Maputo', 'Ciego de Ávila', 'Cienfuegos', 'Cluj', 'Coahuila', 'Cochabamba', 'Coimbra', 'Cojedes', 'Colima', 'Colorado', 'Colón', 'Connecticut', 'Constantine', 'Constanța', 'Copperbelt', 'Cordillera', 'Cork', 'Corrientes', 'Corsica', 'Cortés', 'Corum', 'Costa', 'Cross River', 'Cundinamarca', 'Cuscatlán', 'Córdoba', 'DKI Jakarta', 'Da Nang', 'Daegu', 'Daejeon', 'Dagestan', 'Dakar', 'Dar es Salaam', 'Dayr az Zawr', 'Delaware', 'Delhi', 'Delta', 'Denizli', 'Dhaka', 'Dhi Qar', 'Diana', 'Diffa', 'Dire Dawa', 'District of Columbia', 'Distrito Capital', 'Distrito Federal', 'Dix-Huit Montagnes', 'Diyala', 'Diyarbakir', 'Djelfa', 'Djibouti', 'Dnipropetrovsk', 'Doha', 'Dolj', 'Donetsk', 'Donga', 'Drenthe', 'Duarte', 'Dublin', 'Dukala-Abda', 'Durango', 'Durrës', 'Düzce', 'East', 'East Flanders', 'Eastern', 'Eastern Cape', 'Ebonyi', 'Edo', 'El Aaiún', 'El Beni', 'Elazig', 'Elbasan', 'Emilia-Romagna', 'England', 'Entre Ríos', 'Enugu', 'Erzurum', 'Escuintla', 'Eskisehir', 'Espaillat', 'Espírito Santo', 'Estelí', 'Estuaire', 'Extremadura', 'Extreme-Nord', 'Fars', 'Federal Capital Territory', 'Federation of Bosnia and Herzegovina', 'Flemish Brabant', 'Florida', 'Francisco Morazán', 'Free State', 'French Guiana', 'Friesland', 'Friuli-Venecia Julia', 'Fromager', 'Fujian', 'Fukui', 'Fukuoka', 'Fès-Boulemane', 'Galati', 'Galicia', 'Galway', 'Gansu', 'Gauteng', 'Gaziantep', 'Gelderland', 'Geneva', 'Georgia', 'Gezira', 'Gharb-Chrarda-Beni Hssen', 'Gharbia', 'Gisborne', 'Giurgiu', 'Gobolka Woqooyi Galbeed', 'Goiás', 'Golestán', 'Gombe', 'Gomel', 'Gorj', 'Grad Zagreb', 'Granada', 'Grand Casablanca', 'Grand Est', 'Grand Gedeh', 'Granma', 'Great Rift Valley', 'Greater Accra', 'Greater Poland', 'Grodno', 'Groningen', 'Guadeloupe', 'Guanacaste', 'Guanajuato', 'Guangdong', 'Guangxi', 'Guantánamo', 'Guatemala', 'Guayas', 'Guelma', 'Guelmim-Esmara', 'Guerrero', 'Guizhou', 'Gujarat', 'Gulu', 'Gunma', 'Guárico', 'Gyeonggi', 'Gyeongsangnam', 'Győr', 'Gīlān', 'Haifa', 'Hainan', 'Hainaut', 'Hajdú-Bihar', 'Halland', 'Hamburg', 'Hamedan', 'Hanoi', 'Harare', 'Harjumaa', 'Haryana', 'Hatay', 'Haut-Sassandra', 'Haute-Matsiatra', 'Hauts-de-France', "Hawke's Bay", 'Hebei', 'Hedmark', 'Heilongjiang', 'Henan', 'Herat', 'Hesse', 'Hidalgo', 'Hims', 'Hiroshima', 'Ho Chi Minh City', 'Hokkaido', 'Holguín', 'Hong Kong', 'Hordaland', 'Hormozgān', 'Hradec Králové', 'Huambo', 'Hubei', 'Huehuetenango', 'Huila', 'Hunan', 'Hunedoara', 'Hyogo', 'Iasi', 'Ibaraki', 'Ibb', 'Ica', 'Idaho', 'Igdir', 'Ilam', 'Illes Balears', 'Illinois', 'Imereti', 'Imo', 'Indiana', 'Inhambane', 'Inner Mongolia', 'Iowa', 'Irbid', 'Iringa', 'Irkutsk', 'Isfahan', 'Ishikawa', 'Isla de la Juventud', 'Isparta', 'Istanbul', 'Ivano-Frankivsk', 'Ivanovo', 'Izmir', 'Jalisco', 'Jambi', 'Jammu and Kashmir', 'Jawa Barat', 'Jawa Tengah', 'Jawa Timur', 'Jeju', 'Jerusalem', 'Jewish Autonomous Oblast', 'Jharkhand', 'Jiangsu', 'Jiangxi', 'Jilin', 'Jinja', 'Jizan', 'Jizzakh', 'Jubbada Hoose', 'Jujuy', 'Junín', 'Kabardia-Balkaria', 'Kabarole', 'Kabul', 'Kaduna', 'Kafr el-Sheikh', 'Kagawa', 'Kahramanmaraş', 'Kalimantan Barat', 'Kalimantan Selatan', 'Kalimantan Timur', 'Kaliningrad', 'Kaluga', 'Kampala', 'Kanagawa', 'Kandahar', 'Kankan', 'Kano', 'Kansas', 'Kara', 'Karaganda', 'Karaman', 'Karbala', 'Karnataka', 'Kars', 'Kasai-Occidental', 'Kasai-Oriental', 'Kasala', 'Kastamonu', 'Katanga', 'Katsina', 'Kaunas', 'Kayes', 'Kayseri', 'Kentucky', 'Kerala', 'Kerman', 'Kermanshah', 'Khanh Hoa', 'Kharkiv', 'Khartoum', 'Khatlon', 'Kherson', 'Khmelnytskyi', 'Khomas', 'Khorasan Razavi', 'Khorezm', 'Khulna', 'Khuzestan', 'Khyber Pakhtunkhwa', 'Kigali', 'Kigoma', 'Kilimanjaro', 'Kilis', 'Kindia', 'Kinshasa', 'Kirovohrad', 'Kirsehir', 'Kiên Giang', 'Klaipėda', 'Kocaeli', 'Kongo Central', 'Konya', 'Kor', 'Kostanay', 'Kuala Lumpur', 'Kumanovo', 'Kurdistan', 'KwaZulu-Natal', 'Kwara', 'Kymenlaakso', 'Kütahya', 'La Libertad', 'La Pampa', 'La Paz', 'La Rioja', 'La Romana', 'La Vega', 'Lacs', 'Laghouat', 'Lagos', 'Lagunes', 'Lambayeque', 'Lara', 'Las Tunas', 'Lazio', 'Lebap', 'Lesser Poland', 'León', 'Liaoning', 'Liberec', 'Liguria', 'Lima', 'Limburg', 'Limpopo', 'Lisboa', 'Litoral', 'Littoral', 'Liège', 'Ljubljana', 'Lodz', 'Lombardy', 'Lorestan', 'Loreto', 'Lori', 'Los Lagos', 'Los Ríos', 'Louisiana', 'Lower Saxony', 'Luanda', 'Lublin', 'Lubusz', 'Lucerne', 'Lugansk', 'Lusaka', 'Luxembourg', 'Lviv', 'Madhya Pradesh', 'Madrid', 'Magallanes and Chilean Antarctica', 'Magdalena', 'Maharashtra', 'Maine', 'Malanje', 'Malatya', 'Maluku', 'Manabí', 'Managua', 'Manawatu-Wanganui', 'Mandoul', 'Manica', 'Manicalandia', 'Maniema', 'Manipur', 'Manisa', 'Manitoba', 'Manzini', 'Maputo', 'Mara', 'Maradi', 'Maramures', 'Marañón', 'Marche', 'Mardin', 'Maritime Region', 'Markaz', 'Marlborough', 'Marrakech-Tensift-Al Hauz', 'Martinique', 'Mary', 'Maryland', 'Masaya', 'Maseru', 'Mashonaland West', 'Massachusetts', 'Matagalpa', 'Matanzas', 'Mato Grosso', 'Mato Grosso do Sul', 'Matruh', 'Mayabeque', 'Maysan', 'Mazovia', 'Mbeya', 'Mecca', 'Mecklenburg-Vorpommern', 'Medina', 'Mehedinti', 'Meknès-Tafilalet', 'Melilla', 'Mendoza', 'Menia', 'Mersin', 'Meta', 'Michigan', 'Michoacán', 'Mie', 'Minas Gerais', 'Minnesota', 'Miranda', 'Misiones', 'Mississippi', 'Missouri', 'Misurata', 'Monagas', 'Mono', 'Monseñor Nouel', 'Montana', 'Montevideo', 'Montserrado', 'Mopti', 'Moquegua', 'Moravia-Silesia', 'Morelos', 'Morogoro', 'Moscow', 'Mostaganem', 'Mpumalanga', 'Mtwara', 'Muharraq', 'Murcia', 'Mures', 'Muscat', 'Mwanza', 'Mykolayiv', 'Mérida', 'México', 'Māzandarān', 'Nagano', 'Nagasaki', 'Nairobi', 'Nakhon Ratchasima', 'Namangan', 'Namibe', 'Nampula', 'Namur', 'Nangarhar', 'Nariño', 'National Capital Territory', 'Navarra', 'Nayarit', 'Neamt', 'Nebraska', 'Negeri Sembilan', 'Nelson', 'Neuquén', 'Nevada', 'Nevsehir', 'New Hampshire', 'New Jersey', 'New Mexico', 'New South Wales', 'New York', 'Newfoundland and Labrador', 'Niamey', 'Niari', 'Niassa', 'Nicosia', 'Nigde', 'Niger', 'Nineveh', 'Ningxia Hui', 'Nitra', 'Noord-Holland', 'Nord', 'Nord-Ouest', 'Normandy', 'North Brabant', 'North Carolina', 'North Dakota', 'North Lebanon', 'North Rhine-Westphalia', 'North Santander', 'North West', 'Northern', 'Northern Mindanao', 'Northern Territory', 'Northland', 'Nouakchott', 'Nouvelle-Aquitaine', 'Nova Scotia', 'Novgorod', 'Nueva Esparta', 'Nuevo León', 'Nusa Tenggara Barat', 'Nusa Tenggara Timur', 'Nyanza', 'Nzérékoré', "O'Higgins", 'Oaxaca', 'Occitanie', 'Odisha', 'Ogun', 'Ohio', 'Oita', 'Okayama', 'Oklahoma', 'Olomouc', 'Ondo', 'Ontario', 'Opole', 'Oran', 'Ordu', 'Oregon', 'Orientale Province', 'Oruro', 'Osaka', 'Osh', 'Osijek-Baranja', 'Oslo', 'Osmaniye', 'Osun', 'Otago', 'Ouémé', 'Overijssel', 'Oyo', 'Pahang', 'Panama', 'Panevezys', 'Papua', 'Paramaribo', 'Paraná', 'Paraíba', 'Pará', 'Pavlodar', 'Pays de la Loire', 'Paysandú', 'Pazardzhik', 'Peking', 'Pennsylvania', 'Perak', 'Peravia', 'Pernambuco', 'Pernik', 'Phnom Penh', 'Piauí', 'Pichincha', 'Piedmont', 'Pinar del Río', 'Piura', 'Plateau', 'Plateaux', 'Plovdiv', 'Plzeň', 'Podgorica', 'Podlaskie', 'Poltava', 'Pomerania', 'Port Said', 'Porto', 'Portuguesa', 'Potosí', 'Prague', 'Prahova', 'Primorje-Gorski Kotar', "Provence-Alpes-Côte d'Azur", 'Puducherry', 'Puebla', 'Punjab', 'Puno', 'Pwani', 'Qashqadaryo', 'Qazvin', 'Qina', 'Qinghai', 'Qom', 'Quebec', 'Queensland', 'Querétaro', 'Quezaltenango', 'Quindío', 'Quintana Roo', 'Rabat-Salé-Zemmour-Zaer', 'Rajasthan', 'Rajshahi', 'Ras al-Jaima', 'Red Sea Governorate', 'Region of Southern Denmark', 'Rheinland-Pfalz', 'Rhode Island', 'Riau', 'Rio Grande do Norte', 'Rio Grande do Sul', 'Rio Negro', 'Rio de Janeiro', 'Risaralda', 'Rivera', 'Rivne', 'Riyadh', 'Rize', 'Rogaland', 'Rondônia', 'Roraima', 'Ruvuma', 'Río Tala', 'Sabah', 'Saga', 'Saida', 'Saint-Louis', 'Saitama', 'Saladin', 'Salta', 'Salzburg', 'Samsun', 'San Cristóbal', 'San Fernando', 'San Juan', 'San Luis', 'San Luis Potosí', 'San Miguel', 'San Pedro de Macorís', 'San Salvador', 'Sancti Spíritus', 'Sanliurfa', 'Santa Ana', 'Santa Catarina', 'Santa Caterina', 'Santa Cruz', 'Santa Fe', 'Santander', 'Santiago', 'Santiago de Cuba', 'Santiago del Estero', 'Santo Domingo', 'Sarawak', 'Sardinia', 'Sarre', 'Saskatchewan', 'Satu Mare', 'Savanes', 'Saxony', 'Saxony-Anhalt', 'Scania', 'Schleswig-Holstein', 'Scotland', 'Selangor', 'Semnan', 'Seoul', 'Serbia Central', 'Sergipe', 'Setúbal', 'Sevastopol', 'Shaanxi', 'Shandong', 'Shanghai', 'Shanxi', 'Shinyanga', 'Shizuoka', 'Shkodër', 'Shumen', 'Sibiu', 'Sichuan', 'Sicilia', 'Sidi Bel Abbes', 'Siirt', 'Sikasso', 'Silesia', 'Sinaloa', 'Sind', 'Singapore', 'Sirnak', 'Sistan and Baluchestan', 'Sivas', 'Skikda', 'Sliven', 'Sofala', 'Sofia', 'Sokoto', 'Sonora', 'Sonsonate', 'Souss-Massa-Drâa', 'South', 'South Australia', 'South Carolina', 'South Chungcheong', 'South Dakota', 'South Dublin', 'South East', 'South Holland', 'South Khorasan', 'South Kivu', 'Southern', 'Southland', 'Southwest', 'Southwest Finland', 'Split-Dalmatia', 'St. Gallen', 'Stara Zagora', 'Stavropol', 'Stockholm', 'Styria', 'Suceava', 'Sucre', 'Suhaj', 'Sulawesi Tengah', 'Sulawesi Tenggara', 'Sulawesi Utara', 'Sumatera Barat', 'Sumatera Selatan', 'Sumatera Utara', 'Sumy', 'Surxondaryo', 'Sylhet', 'São Paulo', 'Södermanland', 'Tabasco', 'Tabora', 'Tabuk', 'Tadla-Azilal', 'Taipei', 'Taiz', 'Tamaulipas', 'Tambov', 'Tamil Nadu', 'Tanga', 'Tangier-Tétouan', 'Taranaki', 'Tarapacá', 'Tarija', 'Tartu', 'Tasmania', 'Taza-Al Hoceima-Taounate', 'Tbilisi', 'Tehran', 'Tekirdag', 'Tel Aviv', 'Telangana', 'Tennessee', 'Ternopil', 'Tete', 'Texas', 'Thiès', 'Thuringia', 'Tianjin', 'Timis', 'Tipaza', 'Tirol', 'Tizi Ouzou', 'Tlemcen', 'Tocantins', 'Tochigi', 'Tokat', 'Tokyo', 'Tolima', 'Toscana', 'Tottori', 'Trabzon', 'Trengganu', 'Trentino-Alto Adigio', 'Tripura', 'Tunis', 'Táchira', 'Ucayali', 'Ulaanbaatar', 'Ulsan', 'Umbria', 'Upper Austria', 'Upper Demerara-Berbice', 'Upsala', 'Usak', 'Utah', 'Utrecht', 'Uttar Pradesh', 'Uttarakhand', 'Uusimaa', 'Valenciana', 'Valle del Cauca', 'Vallée du Bandama', 'Valparaíso', 'Van', 'Vargas', 'Varna', 'Vaud', 'Veneto', 'Veracruz', 'Vermont', 'Vest-Agder', 'Victoria', 'Vienna', 'Vientiane', 'Villa Clara', 'Vilnius', 'Vinnytsia', 'Virginia', 'Vitsyebsk', 'Vladimir', 'Vlorë', 'Volyn', 'Voronezh', 'Vrancea', 'Vâlcea', 'Värmland', 'Västra Götaland', 'Waikato', 'Wales', 'Washington', 'Wellington', 'West', 'West Bengal', 'West Flanders', 'West Virginia', 'Western', 'Western Australia', 'Western Cape', 'Western Visayas', 'White Nile', 'Wisconsin', 'Xinjiang Uygur', 'Yalova', 'Yamaguchi', 'Yambol', 'Yangon', 'Yaracuy', 'Yaroslavl', 'Yazd', 'Yobe', 'Yogyakarta', 'Yoro', 'Yucatán', 'Yunnan', 'Zacatecas', 'Zagrebačka', 'Zambezia', 'Zamfara', 'Zanjan', 'Zaporizhzhia', 'Zealand', 'Zhambyl', 'Zhejiang', 'Zhytomyr', 'Ziguinchor', 'Zinder', 'Zulia', 'Zürich', 'Çanakkale', 'Équateur', 'Île-de-France', 'Ústí nad Labem', 'Šiauliai', 'Žilina']
Daftar region(wilayah) pada dataset:
['Canada', 'Caribbean', 'Central Africa', 'Central America', 'Central Asia', 'East Africa', 'East of USA', 'Eastern Asia', 'Eastern Europe', 'North Africa', 'Northern Europe', 'Oceania', 'South America', 'South Asia', 'South of  USA ', 'Southeast Asia', 'Southern Africa', 'Southern Europe', 'US Center ', 'West Africa', 'West Asia', 'West of USA ', 'Western Europe']

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [6]:
# Konversi ke CSV
df.to_csv('data_clean/clean_DataCoSupply_Chain.csv', index=False)